default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: tip_your_guide_development
  queue:
    <<: *primary_development
    database: tip_your_guide_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: tip_your_guide_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: tip_your_guide_test

production:
  primary: &primary_production
    <<: *default
    database: tip_your_guide_production
    username: tip_your_guide
    password: <%= ENV["TIP_YOUR_GUIDE_DATABASE_PASSWORD"] %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: tip_your_guide_production_cache
    migrations_paths: db/cache_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cache" } if ENV["DATABASE_URL"] %>
  queue:
    <<: *primary_production
    database: tip_your_guide_production_queue
    migrations_paths: db/queue_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_queue" } if ENV["DATABASE_URL"] %>
  cable:
    <<: *primary_production
    database: tip_your_guide_production_cable
    migrations_paths: db/cable_migrate
    url: <%= URI.parse(ENV["DATABASE_URL"]).tap { |url| url.path += "_cable" } if ENV["DATABASE_URL"] %>
